name: Deploy MERN Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Private EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy MERN App" \
            --parameters commands='[
              "git config --system --add safe.directory /home/ssm-user/apps/MERN-E-Commerce-Store",
              "sudo chown -R ssm-user:ssm-user /home/ssm-user/apps/MERN-E-Commerce-Store",
              "cd /home/ssm-user/apps/MERN-E-Commerce-Store && git pull origin main",
              "cd /home/ssm-user/apps/MERN-E-Commerce-Store && npm install",
              "cd /home/ssm-user/apps/MERN-E-Commerce-Store/frontend && rm -rf dist",
              "cd /home/ssm-user/apps/MERN-E-Commerce-Store/frontend && npm install",
              "cd /home/ssm-user/apps/MERN-E-Commerce-Store/frontend && npm run build",
              "pm2 restart backend",
              "sudo systemctl restart nginx"
            ]'